name: stockpredict
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - torch>=2.1.0
      - torchaudio>=2.1.0
      - torchvision>=0.16.0
      - transformers>=4.38.0
      - tokenizers>=0.15.0
      - pandas>=1.5.3
      - numpy>=1.23.5
      - scikit-learn>=1.2.2
      - matplotlib>=3.7.1
      - seaborn>=0.12.2
      - requests>=2.31.0
      - alpha_vantage>=2.3.1
      - tqdm>=4.66.0
      - jupyterlab>=4.0.0
